# Generated by Django 3.2.14 on 2022-07-31 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(help_text='Type a name and a surname', max_length=100, verbose_name='Full name')),
                ('cpf', models.CharField(help_text='Type your CPF in the following format: 11122233344', max_length=14, primary_key=True, serialize=False, verbose_name='CPF')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone', models.CharField(help_text='Type phone number in the following format: (XX) XXXXX-XXXX for mobile phones or (XX) XXXX-XXXX for landlines.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\([1-9]{2}\\) (?:[2-8]|9[1-9])[0-9]{3}\\-[0-9]{4}$', 'Enter a phone number in the correct format. Mobile phones: (XX) XXXXX-XXXX Landlines: (XX) XXXX-XXXX')], verbose_name='Phone number')),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
        ),
    ]
